module.exports = {
  content: ["./*.html", "./src/**/*.{html,js}"],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-primary-container": "#fff7f5",
              "background": "#f9f9fa",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed-variant": "#474746",
              "primary-fixed-dim": "#ffb4ac",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "outline": "#926e6b",
              "on-primary-fixed-variant": "#93000d",
              "on-secondary": "#ffffff",
              "surface-container-high": "#e8e8e9",
              "primary-fixed": "#ffdad6",
              "surface-bright": "#f9f9fa",
              "primary": "#b70013",
              "secondary-container": "#dfe0e0",
              "inverse-surface": "#2f3132",
              "surface-container-low": "#f3f3f4",
              "on-primary-fixed": "#410002",
              "on-background": "#1a1c1d",
              "inverse-primary": "#ffb4ac",
              "error-container": "#ffdad6",
              "on-secondary-container": "#616363",
              "outline-variant": "#e7bdb8",
              "tertiary-fixed": "#e5e2e1",
              "tertiary": "#5a5a59",
              "secondary": "#5d5f5f",
              "tertiary-container": "#737272",
              "on-surface": "#1a1c1d",
              "on-tertiary": "#ffffff",
              "on-surface-variant": "#5d3f3c",
              "surface-container": "#eeeeef",
              "tertiary-fixed-dim": "#c8c6c5",
              "surface-dim": "#dadadb",
              "on-tertiary-container": "#fbf8f8",
              "secondary-fixed": "#e2e2e2",
              "on-tertiary-fixed": "#1b1c1c",
              "on-error-container": "#93000a",
              "surface-container-highest": "#e2e2e3",
              "on-primary": "#ffffff",
              "on-secondary-fixed-variant": "#454747",
              "secondary-fixed-dim": "#c6c6c7",
              "surface-variant": "#e2e2e3",
              "primary-container": "#e11922",
              "surface-tint": "#c00015",
              "inverse-on-surface": "#f0f1f2",
              "on-secondary-fixed": "#1a1c1c",
              "surface": "#f9f9fa"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "container-max": "1200px",
              "gutter": "24px",
              "lg": "48px",
              "base": "8px",
              "xs": "4px",
              "md": "24px",
              "sm": "12px",
              "xl": "80px"
          },
          "fontFamily": {
              "label-sm": ["Plus Jakarta Sans", "sans-serif"],
              "h1": ["Plus Jakarta Sans", "sans-serif"],
              "h3": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Plus Jakarta Sans", "sans-serif"],
              "body-md": ["Plus Jakarta Sans", "sans-serif"],
              "h4": ["Plus Jakarta Sans", "sans-serif"],
              "h2": ["Plus Jakarta Sans", "sans-serif"],
              "sans": ["Plus Jakarta Sans", "sans-serif"],
              "heading": ["Plus Jakarta Sans", "sans-serif"]
          },
          "fontSize": {
              "label-sm": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "h1": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h3": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h4": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "h2": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
