// Data yang sering berubah diletakkan di sini supaya halaman HTML tetap ringan.
// Edit daftar ini untuk update unit bisnis, alamat, jam operasional, link, cover, dan galeri.
const numberedAssets = (folder, prefix, count, ext, start = 1) => (
    Array.from({ length: count }, (_, index) => {
        const number = String(start + index).padStart(2, '0');
        return `assets/img/${folder}/${prefix}-${number}.${ext}`;
    })
);

window.MSG_DATA = {
    site: {
        companyName: 'PT. Mari Sukses Gemilang',
        shortName: 'MSG',
        description: 'Membangun jaringan bisnis lifestyle terkemuka di Indonesia, berfokus pada kualitas, inovasi, dan pengalaman pelanggan yang luar biasa.',
        email: '',
        phone: '',
    },

    navigation: [
        { label: 'Beranda', href: 'index.html' },
        { label: 'Tentang Kami', href: 'about.html' },
        { label: 'Unit Bisnis', href: 'business.html' },
        { label: 'Galeri', href: 'gallery.html' },
        { label: 'Berita', href: 'news.html' },
    ],

    businessCategories: [
        {
            id: 'fb',
            navLabel: 'Makanan & Minuman (F&B)',
            title: 'Makanan & Minuman (F&B)',
            description: 'Jaringan kuliner dan kafe untuk melengkapi pengalaman Anda.',
            icon: 'restaurant',
        },
        {
            id: 'lifestyle',
            navLabel: 'Olahraga & Hiburan',
            title: 'Olahraga & Hiburan',
            description: 'Fasilitas olahraga premium dan pusat hiburan keluarga.',
            icon: 'sports_tennis',
        },
        {
            id: 'retail',
            navLabel: 'Retail & Perhiasan',
            title: 'Retail & Perhiasan',
            description: 'Koleksi perhiasan eksklusif dan layanan retail berkualitas tinggi.',
            icon: 'diamond',
        },
    ],

    businessUnits: [
        {
            id: 'j-chicken-tuparev',
            name: 'J Chicken Tuparev',
            categoryId: 'fb',
            label: 'F&B',
            image: 'assets/img/j-chicken-tprv/j-chicken-tprv-photo-01.jpg',
            location: 'Jl. Tuparev, Cirebon [Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=j-chicken-tuparev',
        },
        {
            id: 'j-chicken-ciledug',
            name: 'J Chicken Ciledug',
            categoryId: 'fb',
            label: 'F&B',
            image: 'assets/img/j-chicken-ciledug/j-chicken-ciledug-photo-01.jpg',
            location: 'Ciledug, Cirebon',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=j-chicken-ciledug',
        },
        {
            id: 'ulon-signature-tuparev',
            name: 'Ulon Signature Tuparev',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-01.jpg',
            location: 'Jl. Tuparev, Cirebon',
            hours: '09.00 - 22.00 WIB',
            url: 'unit-detail.html?id=ulon-signature-tuparev',
        },
        {
            id: 'ulon-ciledug',
            name: 'Ulon Ciledug',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/ulon-coffee-cld/ulon-coffee-cld-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=ulon-ciledug',
        },
        {
            id: 'araichi-ramen',
            name: 'Araichi Ramen',
            categoryId: 'fb',
            label: 'F&B',
            image: 'assets/img/araichi-ramen/araichi-ramen-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=araichi-ramen',
        },
        {
            id: 'luuca-ciledug',
            name: 'Luuca Ciledug',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/luuca-ciledug/luuca-ciledug-photo-01.jpg',
            location: 'Ciledug, Cirebon',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=luuca-ciledug',
        },
        {
            id: 'momoyo',
            name: 'Momoyo',
            categoryId: 'fb',
            label: 'F&B',
            image: 'https://images.unsplash.com/photo-1563805042-7684c8a9e9cb?q=80&w=2027',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'ulon-pekanbaru',
            name: 'Ulon Pekanbaru',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=ulon-pekanbaru',
        },
        {
            id: 'grandmonde',
            name: 'Grandmonde',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/grandmonde/grandmonde-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=grandmonde',
        },
        {
            id: 'padelnis-sport',
            name: 'Padelnis Sport',
            categoryId: 'lifestyle',
            label: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-01.jpg',
            location: 'Jln. Tanda Barat Kel. Kebonbaru Kec. Kejaksaan Kota Cirebon',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=padelnis-sport',
        },
        {
            id: 'victory-billiard',
            name: 'Victory Billiard',
            categoryId: 'lifestyle',
            label: 'Hiburan',
            image: 'https://images.unsplash.com/photo-1587889150064-075e7a9e6eb1?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'toko-mas-an-an',
            name: 'Toko Mas An An',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1599643478524-fb66f70a00d8?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'complete-mulia-arjawinangun',
            name: 'Toko Mas Complete Mulia Arjawinangun',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'complete-mulia-purwakarta',
            name: 'Toko Mas Complete Mulia Purwakarta',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1573408301145-b98c4af01158?q=80&w=2069',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
            status: 'Masih Renovasi',
        },
    ],

    unitDetails: {
        'j-chicken-tuparev': {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'J Chicken Tuparev Cirebon',
            description: [
                'J-Chicken Tuparev adalah restoran fast food ayam crispy di kawasan Tuparev, Cirebon, yang menghadirkan pengalaman makan cepat saji dengan suasana modern, nyaman, dan cocok untuk berbagai kalangan. Dikenal dengan menu ayam goreng renyah, pilihan paket yang terjangkau, serta ambience yang casual, J-Chicken menjadi salah satu destinasi favorit untuk makan bersama teman maupun keluarga.',
                'Mengusung konsep fast food modern dengan cita rasa yang dekat dengan selera lokal, J-Chicken menghadirkan kombinasi kualitas rasa, pelayanan cepat, dan pengalaman dine-in yang nyaman. Tidak hanya menjadi tempat makan, J-Chicken juga aktif membangun koneksi dengan customer melalui pendekatan brand yang fun, youthful, dan dekat dengan lifestyle anak muda.',
                'Berlokasi di kawasan strategis Tuparev yang dikenal sebagai salah satu pusat aktivitas kuliner dan lifestyle di Cirebon, J-Chicken hadir sebagai pilihan untuk menikmati hidangan ayam crispy yang praktis, flavorful, dan cocok dinikmati kapan saja.',
            ],
            photos: numberedAssets('j-chicken-tprv', 'j-chicken-tprv-photo', 11, 'jpg'),
        },
        'j-chicken-ciledug': {
            fullAddress: 'Ciledug, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'J Chicken Ciledug Cirebon',
            description: [
                'J Chicken Ciledug adalah restoran ayam cepat saji dengan suasana kasual yang dirancang untuk makan bersama keluarga, teman, maupun pelanggan yang membutuhkan pilihan praktis untuk take away. Tampilan outlet yang terang dan mudah dikenali memperkuat karakter J Chicken sebagai destinasi F&B yang ramah untuk berbagai usia.',
                'Selain menghadirkan menu ayam crispy dan paket makan harian, J Chicken Ciledug juga aktif menjadi ruang aktivitas pelanggan melalui program ulang tahun, promo keluarga, dan kegiatan komunitas. Area dine-in yang nyaman membuat outlet ini tidak hanya menjadi tempat makan cepat, tetapi juga tempat merayakan momen sederhana dengan pengalaman yang lebih berkesan.',
                'Berlokasi di kawasan Ciledug, J Chicken Ciledug memperluas jangkauan jaringan kuliner MSG dengan menghadirkan layanan yang praktis, suasana yang ceria, dan pendekatan brand yang dekat dengan kebutuhan pelanggan lokal.',
            ],
            facilities: [
                'Dine in',
                'Take away',
                'Area acara pelanggan',
                'Birthday package',
            ],
            photos: numberedAssets('j-chicken-ciledug', 'j-chicken-ciledug-photo', 5, 'jpg'),
        },
        'ulon-signature-tuparev': {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Signature Tuparev Cirebon',
            description: [
                'Ulon Signature adalah destinasi kuliner modern dengan konsep casual dining yang menghadirkan suasana nyaman, kekinian, dan ideal untuk bersantai bersama teman maupun keluarga. Hadir dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas nongkrong, Ulon Signature menciptakan ambience yang hidup namun tetap terasa akrab dan menyenangkan.',
                'Berlokasi di pusat kota, Ulon Signature menawarkan pengalaman bersantap yang lengkap mulai dari variasi menu yang beragam, pilihan minuman yang menyegarkan, hingga fasilitas yang mendukung kenyamanan pengunjung. Dengan pelayanan yang ramah dan suasana yang suportif untuk komunitas, Ulon Signature tidak hanya menjadi tempat makan, tetapi juga ruang komunitas untuk berbagi cerita dan momen berkualitas.',
            ],
            photos: numberedAssets('ulon-signature', 'ulon-signature-photo', 26, 'jpg'),
            videos: numberedAssets('ulon-signature', 'ulon-signature-video', 3, 'mp4'),
        },
        'ulon-ciledug': {
            fullAddress: 'Ciledug, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Coffee Ciledug Cirebon',
            description: [
                'Ulon Coffee Ciledug adalah bagian dari Ulon Coffee yang hadir dengan konsep casual cafe modern, cocok untuk tempat bersantai, nongkrong, atau sekadar menikmati secangkir kopi dalam suasana yang nyaman dan kekinian. Dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas komunitas, Ulon Coffee Ciledug menawarkan pengalaman ngopi yang menyenangkan dan berkualitas.',
                'Berlokasi di kawasan strategis Ciledug, tempat ini menyediakan pilihan menu yang beragam, mulai dari specialty coffee, minuman segar, hingga makanan ringan yang pas untuk menemani waktu santai bersama teman maupun keluarga. Ulon Coffee Ciledug hadir untuk memberikan ruang komunitas yang hidup, nyaman, dan selalu terbuka untuk berbagai kegiatan positif.',
            ],
            photos: [
                ...numberedAssets('ulon-coffee-cld', 'ulon-coffee-cld-photo', 3, 'jpg'),
                ...numberedAssets('ulon-coffee-cld', 'ulon-coffee-cld-photo', 5, 'png', 4),
            ],
        },
        'ulon-pekanbaru': {
            coverImage: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=2070',
            fullAddress: 'Pekanbaru, Riau, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Coffee Pekanbaru',
            description: [
                'Ulon Coffee Pekanbaru adalah bagian dari Ulon Coffee yang hadir dengan konsep casual cafe modern, cocok untuk tempat bersantai, nongkrong, atau sekadar menikmati secangkir kopi dalam suasana yang nyaman dan kekinian. Dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas komunitas, Ulon Coffee Pekanbaru menawarkan pengalaman ngopi yang menyenangkan dan berkualitas.',
                'Berlokasi di kawasan strategis Pekanbaru, tempat ini menyediakan pilihan menu yang beragam, mulai dari specialty coffee, minuman segar, hingga makanan ringan yang pas untuk menemani waktu santai bersama teman maupun keluarga. Ulon Coffee Pekanbaru hadir untuk memberikan ruang komunitas yang hidup, nyaman, dan selalu terbuka untuk berbagai kegiatan positif.',
            ],
            photos: ['https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=2070'],
        },
        'araichi-ramen': {
            fullAddress: 'Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Araichi Ramen Cirebon',
            description: [
                'Araichi Ramen adalah restoran ramen dengan konsep Japanese casual dining yang menghadirkan pengalaman menikmati ramen dengan rasa autentik namun tetap cocok dengan lidah lokal. Dengan open kitchen experience dan suasana yang hangat, Araichi ingin menghadirkan pengalaman makan yang terasa hidup, interaktif, dan memorable bagi setiap customer.',
                'Tidak hanya berfokus pada ramen, Araichi juga menghadirkan berbagai side dish dan menu pendamping yang dirancang untuk melengkapi pengalaman bersantap bersama teman maupun keluarga. Service yang ramah, suasana yang nyaman, dan perhatian terhadap detail menjadi bagian penting dari identitas Araichi dalam membangun hubungan jangka panjang dengan customer.',
            ],
            photos: numberedAssets('araichi-ramen', 'araichi-ramen-photo', 5, 'jpg'),
        },
        'luuca-ciledug': {
            fullAddress: 'Ciledug, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Luuca Ciledug Cirebon',
            description: [
                'Luuca Ciledug adalah destinasi dessert dan coffee dengan karakter visual yang modern, hangat, dan mudah dikenali melalui kombinasi warna hitam, emas, dan elemen soft serve. Outlet ini menghadirkan suasana yang cocok untuk bersantai, menikmati dessert, dan berkumpul dalam momen ringan bersama keluarga maupun teman.',
                'Dengan pilihan soft serve, coffee, dan menu manis lainnya, Luuca Ciledug memperkuat portofolio F&B MSG di segmen lifestyle cafe. Interior yang compact dan bernuansa premium memberikan pengalaman yang terasa berbeda dari outlet cepat saji, tetapi tetap mudah diakses untuk kebutuhan harian pelanggan.',
                'Kehadiran Luuca Ciledug juga membuka ruang untuk aktivitas pelanggan dan komunitas melalui momen opening, gathering, serta kampanye brand yang lebih dekat dengan gaya hidup anak muda dan keluarga.',
            ],
            facilities: [
                'Dine in',
                'Coffee and dessert',
                'Soft serve',
                'Area aktivitas pelanggan',
            ],
            photos: numberedAssets('luuca-ciledug', 'luuca-ciledug-photo', 2, 'jpg'),
        },
        'padelnis-sport': {
            fullAddress: 'Jln. Tanda Barat Kel. Kebonbaru Kec. Kejaksaan Kota Cirebon',
            contact: '+62 859-7504-0780',
            mapQuery: 'Padelnis Sports Jln. Tanda Barat Kebonbaru Kejaksaan Kota Cirebon',
            description: [
                '<strong>"Where Sport Meets Lifestyle"</strong> - PADELNIS hadir sebagai pusat olahraga padel & tenis modern yang dipadukan dengan kafe kontemporer GRANDMONDE, sehingga bukan hanya tempat untuk berolahraga, tetapi juga destinasi gaya hidup.',
                'PADELNIS adalah pusat olahraga dan gaya hidup ikonik di kota Cirebon, tempat ini menghadirkan pengalaman padel & tenis kelas dunia dengan fasilitas berstandar internasional dan suasana yang hangat dan modern. Menyediakan lapangan padel dengan rumput premium Eropa, satu-satunya dan pertama di kota Cirebon. Menyediakan 6 lapangan padel dan 2 lapangan tenis berstandar turnamen.',
                'Menghadirkan kafe gaya hidup yang menyajikan makanan dan minuman sehat dengan konsep modern, menjadikannya tempat yang sempurna untuk berolahraga, bersantai, dan berjejaring. Membawa tren padel ke komunitas Cirebon melalui program komunitas, acara, dan kompetisi. <strong>Disinilah tempat terbaik kamu membuat event, bersosialisasi dan hang out!!!</strong>',
            ],
            facilities: [
                'Parkir',
                'Mushola',
                'Toilet dan Kamar Mandi',
                'Free Wifi',
                'Caffee dan Resto',
                'Tribun Penonton',
                '6 Lapangan Padel',
                '2 Lapangan Tennis',
            ],
            bookingLinks: [
                {
                    label: 'Reservasi by Ayo',
                    href: 'https://link.ayo.co.id/l/bp0StBnq7E-Padelnis-Sports',
                    icon: 'calendar_month',
                },
                {
                    label: 'Reservasi by WhatsApp',
                    href: 'https://wa.me/6285188204429',
                    icon: 'chat',
                },
                {
                    label: 'Layanan Customer Service',
                    href: 'https://wa.me/6285975040780',
                    icon: 'support_agent',
                },
            ],
            photos: numberedAssets('padelnis-sport', 'padelnis-sport-photo', 10, 'jpg'),
        },
        grandmonde: {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Grandmonde Cafe Cirebon',
            description: [
                'Grandmonde adalah destinasi kuliner dan hiburan modern yang menggabungkan pengalaman makan dengan nuansa entertainment dalam satu lokasi yang nyaman dan trendi. Dengan konsep casual dining yang kekinian, Grandmonde menghadirkan berbagai pilihan menu serta fasilitas yang dirancang untuk memenuhi kebutuhan lifestyle anak muda, komunitas, dan keluarga yang ingin bersantai sekaligus bersenang-senang.',
                'Mengusung tema modern dan urban, Grandmonde menciptakan ambience yang hidup namun tetap terasa akrab dan menyenangkan. Kombinasi desain interior yang stylish, pencahayaan yang hangat, serta alur ruang yang nyaman menjadikan Grandmonde sebagai tempat yang ideal untuk berkumpul, menghabiskan waktu bersama, dan menikmati momen berkualitas.',
                'Berlokasi di kawasan strategis, Grandmonde dirancang tidak hanya sekadar tempat makan, tetapi sebagai destinasi lifestyle yang menawarkan pengalaman lengkap antara kuliner, nongkrong, hingga bersantai. Dengan fasilitas yang memadai dan menu yang bervariasi, Grandmonde hadir untuk memberikan pilihan hiburan casual yang mudah dijangkau dan selalu nyaman untuk dikunjungi.',
            ],
            photos: ['assets/img/grandmonde/grandmonde-photo-01.jpg'],
        },
    },

    newsArticles: [
        {
            id: 'j-chicken-ciledug-birthday-package',
            title: 'J Chicken Ciledug Menghadirkan Birthday Package untuk Keluarga',
            category: 'Promo',
            date: '8 Mei 2026',
            dateISO: '2026-05-08',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'assets/img/j-chicken-ciledug/j-chicken-ciledug-photo-03.jpg',
            alt: 'Birthday package J Chicken Ciledug',
            excerpt: 'Program birthday package J Chicken Ciledug memperkuat pengalaman pelanggan melalui dekorasi, aktivitas anak, dan suasana makan bersama yang lebih meriah.',
            lead: 'J Chicken Ciledug memperkenalkan birthday package sebagai pilihan perayaan keluarga dengan suasana ceria dan layanan yang praktis di dalam outlet.',
            content: [
                'Aktivasi birthday package menghadirkan dekorasi tematik, area foto, dan rangkaian kegiatan sederhana untuk anak-anak, sehingga pengalaman makan di J Chicken terasa lebih personal dan menyenangkan.',
                'Program ini memperluas fungsi outlet dari tempat makan cepat saji menjadi ruang perayaan yang mudah diakses oleh keluarga di kawasan Ciledug dan sekitarnya.',
                'Dengan pendekatan yang fun dan family-friendly, J Chicken Ciledug terus membangun hubungan yang lebih dekat dengan pelanggan melalui momen yang relevan dengan kehidupan sehari-hari.',
            ],
            quote: {
                text: 'Kami ingin setiap kunjungan keluarga bisa menjadi pengalaman yang hangat, bukan hanya transaksi makan.',
                by: 'J Chicken Ciledug Team',
            },
            tags: ['J Chicken', 'Birthday Package', 'Family', 'Ciledug'],
        },
        {
            id: 'j-chicken-ciledug-community-activity',
            title: 'Aktivitas Komunitas di J Chicken Ciledug Menghidupkan Area Dine-In',
            category: 'Event',
            date: '15 Maret 2026',
            dateISO: '2026-03-15',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'assets/img/j-chicken-ciledug/j-chicken-ciledug-photo-04.jpg',
            alt: 'Aktivitas komunitas J Chicken Ciledug',
            excerpt: 'Area dine-in J Chicken Ciledug menjadi ruang aktivitas komunitas yang mempertemukan pelanggan dengan pengalaman brand yang lebih dekat dan interaktif.',
            lead: 'J Chicken Ciledug mendukung aktivitas komunitas di dalam outlet sebagai cara membangun pengalaman pelanggan yang lebih hidup, hangat, dan kolaboratif.',
            content: [
                'Kegiatan komunitas memanfaatkan area dine-in sebagai tempat berkumpul, berbagi aktivitas, dan menikmati menu J Chicken dalam format yang lebih interaktif.',
                'Pendekatan ini membuat outlet semakin dekat dengan pelanggan lokal, terutama komunitas keluarga dan anak muda yang membutuhkan tempat nyaman untuk beraktivitas ringan.',
                'Melalui aktivasi komunitas, J Chicken Ciledug memperkuat posisi sebagai brand F&B yang tidak hanya menawarkan menu praktis, tetapi juga pengalaman sosial yang menyenangkan.',
            ],
            quote: {
                text: 'Outlet yang aktif bersama komunitas akan terasa lebih dekat dengan pelanggan dan lingkungan sekitarnya.',
                by: 'Corporate Communications MSG',
            },
            tags: ['Community', 'J Chicken', 'Event', 'Ciledug'],
        },
        {
            id: 'luuca-ciledug-opening',
            title: 'Luuca Ciledug Hadir dengan Konsep Dessert dan Coffee Modern',
            category: 'Event',
            date: '13 Maret 2026',
            dateISO: '2026-03-13',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'assets/img/luuca-ciledug/luuca-ciledug-photo-01.jpg',
            alt: 'Pembukaan Luuca Ciledug',
            excerpt: 'Luuca Ciledug memperluas portofolio F&B MSG melalui konsep dessert dan coffee yang modern, compact, dan dekat dengan kebutuhan pelanggan lokal.',
            lead: 'PT. Mari Sukses Gemilang memperkenalkan Luuca Ciledug sebagai destinasi dessert dan coffee terbaru dengan nuansa modern dan pengalaman pelanggan yang hangat.',
            content: [
                'Outlet ini hadir dengan karakter visual hitam dan emas yang kuat, area layanan yang compact, serta pilihan menu dessert dan coffee yang mudah dinikmati untuk kunjungan singkat maupun momen berkumpul.',
                'Kehadiran Luuca Ciledug menjadi bagian dari pengembangan jaringan F&B MSG di segmen lifestyle cafe, melengkapi portofolio yang sudah berkembang di area Cirebon dan sekitarnya.',
                'Melalui opening ini, MSG terus memperkuat pengalaman pelanggan yang relevan dengan kebiasaan hangout, pencarian dessert, dan kebutuhan ruang santai yang praktis di kawasan Ciledug.',
            ],
            quote: {
                text: 'Luuca Ciledug dirancang untuk menjadi tempat singgah yang ringan, modern, dan dekat dengan momen harian pelanggan.',
                by: 'Corporate Communications MSG',
            },
            tags: ['Luuca', 'Ciledug', 'Dessert', 'Coffee'],
        },
        {
            id: 'activity-luuca-ciledug',
            title: 'Aktivitas Pelanggan Luuca Ciledug Memperkuat Nuansa Lifestyle Cafe',
            category: 'Aktivitas',
            date: '13 Maret 2026',
            dateISO: '2026-03-13',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'assets/img/luuca-ciledug/luuca-ciledug-photo-02.jpg',
            alt: 'Aktivitas pelanggan di Luuca Ciledug',
            excerpt: 'Aktivitas pelanggan di Luuca Ciledug menunjukkan potensi outlet sebagai ruang dessert, coffee, dan gathering yang compact tetapi hidup.',
            lead: 'Luuca Ciledug mulai menjadi ruang aktivitas pelanggan yang memadukan suasana cafe modern, layanan dessert, dan momen berkumpul yang nyaman.',
            content: [
                'Interior Luuca yang bernuansa gelap, hangat, dan premium memberikan latar yang kuat untuk kegiatan pelanggan, mulai dari gathering kecil sampai aktivitas brand.',
                'Kombinasi coffee, dessert, dan soft serve memperkuat positioning Luuca sebagai tempat singgah yang ringan tetapi tetap terasa stylish untuk pelanggan muda maupun keluarga.',
                'Aktivitas ini menjadi bagian dari cara MSG mengembangkan outlet F&B yang tidak hanya menjual menu, tetapi juga membangun suasana dan pengalaman yang mudah diingat.',
            ],
            quote: {
                text: 'Cafe yang baik memberi alasan bagi pelanggan untuk datang, tinggal, dan kembali lagi.',
                by: 'Luuca Ciledug Team',
            },
            tags: ['Luuca', 'Lifestyle Cafe', 'Activity', 'Dessert'],
        },
    ],

    galleryFilters: [
        { id: 'all', label: 'Semua Galeri' },
        { id: 'fnb', label: 'F&B' },
        { id: 'cafe', label: 'Cafe' },
        { id: 'olahraga', label: 'Olahraga' },
    ],

    galleryItems: [
        {
            title: 'J Chicken Tuparev',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/j-chicken-tprv/j-chicken-tprv-photo-01.jpg',
            alt: 'J Chicken Tuparev',
        },
        {
            title: 'J Chicken Ciledug',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/j-chicken-ciledug/j-chicken-ciledug-photo-01.jpg',
            alt: 'J Chicken Ciledug',
        },
        {
            title: 'Birthday Package J Chicken Ciledug',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/j-chicken-ciledug/j-chicken-ciledug-photo-03.jpg',
            alt: 'Birthday package J Chicken Ciledug',
        },
        {
            title: 'Ulon Signature Tuparev',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-01.jpg',
            alt: 'Ulon Signature Tuparev',
        },
        {
            title: 'Padelnis Sport',
            categoryId: 'olahraga',
            categoryLabel: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-01.jpg',
            alt: 'Padelnis Sport Cirebon',
        },
        {
            title: 'Araichi Ramen',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/araichi-ramen/araichi-ramen-photo-01.jpg',
            alt: 'Araichi Ramen',
        },
        {
            title: 'Luuca Ciledug',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/luuca-ciledug/luuca-ciledug-photo-01.jpg',
            alt: 'Luuca Ciledug',
        },
        {
            title: 'Aktivitas Luuca Ciledug',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/luuca-ciledug/luuca-ciledug-photo-02.jpg',
            alt: 'Aktivitas pelanggan Luuca Ciledug',
        },
        {
            title: 'Ulon Ciledug',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-coffee-cld/ulon-coffee-cld-photo-01.jpg',
            alt: 'Ulon Coffee Ciledug',
        },
        {
            title: 'Grandmonde',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/grandmonde/grandmonde-photo-01.jpg',
            alt: 'Grandmonde',
        },
        {
            title: 'Interior Ulon Signature',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-03.jpg',
            alt: 'Ulon Signature Interior',
        },
        {
            title: 'Fasilitas Padelnis Sport',
            categoryId: 'olahraga',
            categoryLabel: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-02.jpg',
            alt: 'Padelnis Sport Facility',
        },
    ],
};
