// Data yang sering berubah diletakkan di sini supaya halaman HTML tetap ringan.
// Edit daftar ini untuk update unit bisnis, alamat, jam operasional, link, cover, dan galeri.
const numberedAssets = (folder, prefix, count, ext, start = 1) => (
    Array.from({ length: count }, (_, index) => {
        const number = String(start + index).padStart(2, '0');
        return `assets/img/${folder}/${prefix}-${number}.${ext}`;
    })
);

window.MSG_DATA = {
    site: {
        companyName: 'PT. Mari Sukses Gemilang',
        shortName: 'MSG',
        description: 'Membangun jaringan bisnis lifestyle terkemuka di Indonesia, berfokus pada kualitas, inovasi, dan pengalaman pelanggan yang luar biasa.',
        email: '',
        phone: '',
    },

    navigation: [
        { label: 'Beranda', href: 'index.html' },
        { label: 'Tentang Kami', href: 'about.html' },
        { label: 'Unit Bisnis', href: 'business.html' },
        { label: 'Galeri', href: 'gallery.html' },
        { label: 'Berita', href: 'news.html' },
    ],

    businessCategories: [
        {
            id: 'fb',
            navLabel: 'Makanan & Minuman (F&B)',
            title: 'Makanan & Minuman (F&B)',
            description: 'Jaringan kuliner dan kafe untuk melengkapi pengalaman Anda.',
            icon: 'restaurant',
        },
        {
            id: 'lifestyle',
            navLabel: 'Olahraga & Hiburan',
            title: 'Olahraga & Hiburan',
            description: 'Fasilitas olahraga premium dan pusat hiburan keluarga.',
            icon: 'sports_tennis',
        },
        {
            id: 'retail',
            navLabel: 'Retail & Perhiasan',
            title: 'Retail & Perhiasan',
            description: 'Koleksi perhiasan eksklusif dan layanan retail berkualitas tinggi.',
            icon: 'diamond',
        },
    ],

    businessUnits: [
        {
            id: 'j-chicken-tuparev',
            name: 'J Chicken Tuparev',
            categoryId: 'fb',
            label: 'F&B',
            image: 'assets/img/j-chicken-tprv/j-chicken-tprv-photo-01.jpg',
            location: 'Jl. Tuparev, Cirebon [Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=j-chicken-tuparev',
        },
        {
            id: 'j-chicken-ciledug',
            name: 'J Chicken Ciledug',
            categoryId: 'fb',
            label: 'F&B',
            image: 'https://images.unsplash.com/photo-1569058242253-1df250a26eb5?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'ulon-signature-tuparev',
            name: 'Ulon Signature Tuparev',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-01.jpg',
            location: 'Jl. Tuparev, Cirebon',
            hours: '09.00 - 22.00 WIB',
            url: 'unit-detail.html?id=ulon-signature-tuparev',
        },
        {
            id: 'ulon-ciledug',
            name: 'Ulon Ciledug',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/ulon-coffee-cld/ulon-coffee-cld-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=ulon-ciledug',
        },
        {
            id: 'araichi-ramen',
            name: 'Araichi Ramen',
            categoryId: 'fb',
            label: 'F&B',
            image: 'assets/img/araichi-ramen/araichi-ramen-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=araichi-ramen',
        },
        {
            id: 'luuca-ciledug',
            name: 'Luuca Ciledug',
            categoryId: 'fb',
            label: 'F&B',
            image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=2064',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'momoyo',
            name: 'Momoyo',
            categoryId: 'fb',
            label: 'F&B',
            image: 'https://images.unsplash.com/photo-1563805042-7684c8a9e9cb?q=80&w=2027',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'ulon-pekanbaru',
            name: 'Ulon Pekanbaru',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=ulon-pekanbaru',
        },
        {
            id: 'grandmonde',
            name: 'Grandmonde',
            categoryId: 'fb',
            label: 'Cafe',
            image: 'assets/img/GRANDMONDE/grandmonde-photo-01.jpg',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=grandmonde',
        },
        {
            id: 'padelnis-sport',
            name: 'Padelnis Sport',
            categoryId: 'lifestyle',
            label: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-01.jpg',
            location: 'Jln. Tanda Barat Kel. Kebonbaru Kec. Kejaksaan Kota Cirebon',
            hours: 'Jam Operasional: TBC',
            url: 'unit-detail.html?id=padelnis-sport',
        },
        {
            id: 'victory-billiard',
            name: 'Victory Billiard',
            categoryId: 'lifestyle',
            label: 'Hiburan',
            image: 'https://images.unsplash.com/photo-1587889150064-075e7a9e6eb1?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'toko-mas-an-an',
            name: 'Toko Mas An An',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1599643478524-fb66f70a00d8?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'complete-mulia-arjawinangun',
            name: 'Toko Mas Complete Mulia Arjawinangun',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=2070',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
        },
        {
            id: 'complete-mulia-purwakarta',
            name: 'Toko Mas Complete Mulia Purwakarta',
            categoryId: 'retail',
            label: 'Retail',
            image: 'https://images.unsplash.com/photo-1573408301145-b98c4af01158?q=80&w=2069',
            location: '[Detail Alamat Menyusul]',
            hours: 'Jam Operasional: TBC',
            url: '404.html',
            status: 'Masih Renovasi',
        },
    ],

    unitDetails: {
        'j-chicken-tuparev': {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'J Chicken Tuparev Cirebon',
            description: [
                'J-Chicken Tuparev adalah restoran fast food ayam crispy di kawasan Tuparev, Cirebon, yang menghadirkan pengalaman makan cepat saji dengan suasana modern, nyaman, dan cocok untuk berbagai kalangan. Dikenal dengan menu ayam goreng renyah, pilihan paket yang terjangkau, serta ambience yang casual, J-Chicken menjadi salah satu destinasi favorit untuk makan bersama teman maupun keluarga.',
                'Mengusung konsep fast food modern dengan cita rasa yang dekat dengan selera lokal, J-Chicken menghadirkan kombinasi kualitas rasa, pelayanan cepat, dan pengalaman dine-in yang nyaman. Tidak hanya menjadi tempat makan, J-Chicken juga aktif membangun koneksi dengan customer melalui pendekatan brand yang fun, youthful, dan dekat dengan lifestyle anak muda.',
                'Berlokasi di kawasan strategis Tuparev yang dikenal sebagai salah satu pusat aktivitas kuliner dan lifestyle di Cirebon, J-Chicken hadir sebagai pilihan untuk menikmati hidangan ayam crispy yang praktis, flavorful, dan cocok dinikmati kapan saja.',
            ],
            photos: numberedAssets('j-chicken-tprv', 'j-chicken-tprv-photo', 11, 'jpg'),
        },
        'ulon-signature-tuparev': {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Signature Tuparev Cirebon',
            description: [
                'Ulon Signature adalah destinasi kuliner modern dengan konsep casual dining yang menghadirkan suasana nyaman, kekinian, dan ideal untuk bersantai bersama teman maupun keluarga. Hadir dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas nongkrong, Ulon Signature menciptakan ambience yang hidup namun tetap terasa akrab dan menyenangkan.',
                'Berlokasi di pusat kota, Ulon Signature menawarkan pengalaman bersantap yang lengkap mulai dari variasi menu yang beragam, pilihan minuman yang menyegarkan, hingga fasilitas yang mendukung kenyamanan pengunjung. Dengan pelayanan yang ramah dan suasana yang suportif untuk komunitas, Ulon Signature tidak hanya menjadi tempat makan, tetapi juga ruang komunitas untuk berbagi cerita dan momen berkualitas.',
            ],
            photos: numberedAssets('ulon-signature', 'ulon-signature-photo', 26, 'jpg'),
            videos: numberedAssets('ulon-signature', 'ulon-signature-video', 3, 'mp4'),
        },
        'ulon-ciledug': {
            fullAddress: 'Ciledug, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Coffee Ciledug Cirebon',
            description: [
                'Ulon Coffee Ciledug adalah bagian dari Ulon Coffee yang hadir dengan konsep casual cafe modern, cocok untuk tempat bersantai, nongkrong, atau sekadar menikmati secangkir kopi dalam suasana yang nyaman dan kekinian. Dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas komunitas, Ulon Coffee Ciledug menawarkan pengalaman ngopi yang menyenangkan dan berkualitas.',
                'Berlokasi di kawasan strategis Ciledug, tempat ini menyediakan pilihan menu yang beragam, mulai dari specialty coffee, minuman segar, hingga makanan ringan yang pas untuk menemani waktu santai bersama teman maupun keluarga. Ulon Coffee Ciledug hadir untuk memberikan ruang komunitas yang hidup, nyaman, dan selalu terbuka untuk berbagai kegiatan positif.',
            ],
            photos: [
                ...numberedAssets('ulon-coffee-cld', 'ulon-coffee-cld-photo', 3, 'jpg'),
                ...numberedAssets('ulon-coffee-cld', 'ulon-coffee-cld-photo', 5, 'png', 4),
            ],
        },
        'ulon-pekanbaru': {
            coverImage: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=2070',
            fullAddress: 'Pekanbaru, Riau, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Ulon Coffee Pekanbaru',
            description: [
                'Ulon Coffee Pekanbaru adalah bagian dari Ulon Coffee yang hadir dengan konsep casual cafe modern, cocok untuk tempat bersantai, nongkrong, atau sekadar menikmati secangkir kopi dalam suasana yang nyaman dan kekinian. Dengan desain interior yang stylish, pencahayaan yang hangat, serta area yang dirancang untuk mendukung aktivitas komunitas, Ulon Coffee Pekanbaru menawarkan pengalaman ngopi yang menyenangkan dan berkualitas.',
                'Berlokasi di kawasan strategis Pekanbaru, tempat ini menyediakan pilihan menu yang beragam, mulai dari specialty coffee, minuman segar, hingga makanan ringan yang pas untuk menemani waktu santai bersama teman maupun keluarga. Ulon Coffee Pekanbaru hadir untuk memberikan ruang komunitas yang hidup, nyaman, dan selalu terbuka untuk berbagai kegiatan positif.',
            ],
            photos: ['https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=2070'],
        },
        'araichi-ramen': {
            fullAddress: 'Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Araichi Ramen Cirebon',
            description: [
                'Araichi Ramen adalah restoran ramen dengan konsep Japanese casual dining yang menghadirkan pengalaman menikmati ramen dengan rasa autentik namun tetap cocok dengan lidah lokal. Dengan open kitchen experience dan suasana yang hangat, Araichi ingin menghadirkan pengalaman makan yang terasa hidup, interaktif, dan memorable bagi setiap customer.',
                'Tidak hanya berfokus pada ramen, Araichi juga menghadirkan berbagai side dish dan menu pendamping yang dirancang untuk melengkapi pengalaman bersantap bersama teman maupun keluarga. Service yang ramah, suasana yang nyaman, dan perhatian terhadap detail menjadi bagian penting dari identitas Araichi dalam membangun hubungan jangka panjang dengan customer.',
            ],
            photos: numberedAssets('araichi-ramen', 'araichi-ramen-photo', 5, 'jpg'),
            videos: numberedAssets('araichi-ramen', 'araichi-ramen-video', 6, 'mp4'),
        },
        'padelnis-sport': {
            fullAddress: 'Jln. Tanda Barat Kel. Kebonbaru Kec. Kejaksaan Kota Cirebon',
            contact: '+62 859-7504-0780',
            mapQuery: 'Padelnis Sports Jln. Tanda Barat Kebonbaru Kejaksaan Kota Cirebon',
            description: [
                '<strong>"Where Sport Meets Lifestyle"</strong> - PADELNIS hadir sebagai pusat olahraga padel & tenis modern yang dipadukan dengan kafe kontemporer GRANDMONDE, sehingga bukan hanya tempat untuk berolahraga, tetapi juga destinasi gaya hidup.',
                'PADELNIS adalah pusat olahraga dan gaya hidup ikonik di kota Cirebon, tempat ini menghadirkan pengalaman padel & tenis kelas dunia dengan fasilitas berstandar internasional dan suasana yang hangat dan modern. Menyediakan lapangan padel dengan rumput premium Eropa, satu-satunya dan pertama di kota Cirebon. Menyediakan 6 lapangan padel dan 2 lapangan tenis berstandar turnamen.',
                'Menghadirkan kafe gaya hidup yang menyajikan makanan dan minuman sehat dengan konsep modern, menjadikannya tempat yang sempurna untuk berolahraga, bersantai, dan berjejaring. Membawa tren padel ke komunitas Cirebon melalui program komunitas, acara, dan kompetisi. <strong>Disinilah tempat terbaik kamu membuat event, bersosialisasi dan hang out!!!</strong>',
            ],
            facilities: [
                'Parkir',
                'Mushola',
                'Toilet dan Kamar Mandi',
                'Free Wifi',
                'Caffee dan Resto',
                'Tribun Penonton',
                '6 Lapangan Padel',
                '2 Lapangan Tennis',
            ],
            bookingLinks: [
                {
                    label: 'Reservasi by Ayo',
                    href: 'https://link.ayo.co.id/l/bp0StBnq7E-Padelnis-Sports',
                    icon: 'calendar_month',
                },
                {
                    label: 'Reservasi by WhatsApp',
                    href: 'https://wa.me/6285188204429',
                    icon: 'chat',
                },
                {
                    label: 'Layanan Customer Service',
                    href: 'https://wa.me/6285975040780',
                    icon: 'support_agent',
                },
            ],
            photos: numberedAssets('padelnis-sport', 'padelnis-sport-photo', 10, 'jpg'),
        },
        grandmonde: {
            fullAddress: 'Jl. Tuparev, Cirebon, Jawa Barat, Indonesia.',
            contact: '+62 812-3456-7890',
            mapQuery: 'Grandmonde Cafe Cirebon',
            description: [
                'Grandmonde adalah destinasi kuliner dan hiburan modern yang menggabungkan pengalaman makan dengan nuansa entertainment dalam satu lokasi yang nyaman dan trendi. Dengan konsep casual dining yang kekinian, Grandmonde menghadirkan berbagai pilihan menu serta fasilitas yang dirancang untuk memenuhi kebutuhan lifestyle anak muda, komunitas, dan keluarga yang ingin bersantai sekaligus bersenang-senang.',
                'Mengusung tema modern dan urban, Grandmonde menciptakan ambience yang hidup namun tetap terasa akrab dan menyenangkan. Kombinasi desain interior yang stylish, pencahayaan yang hangat, serta alur ruang yang nyaman menjadikan Grandmonde sebagai tempat yang ideal untuk berkumpul, menghabiskan waktu bersama, dan menikmati momen berkualitas.',
                'Berlokasi di kawasan strategis, Grandmonde dirancang tidak hanya sekadar tempat makan, tetapi sebagai destinasi lifestyle yang menawarkan pengalaman lengkap antara kuliner, nongkrong, hingga bersantai. Dengan fasilitas yang memadai dan menu yang bervariasi, Grandmonde hadir untuk memberikan pilihan hiburan casual yang mudah dijangkau dan selalu nyaman untuk dikunjungi.',
            ],
            photos: ['assets/img/GRANDMONDE/grandmonde-photo-01.jpg'],
        },
    },

    newsArticles: [
        {
            id: 'msg-business-summit',
            title: 'MSG Annual Business Summit: Transforming the Future of Fintech',
            category: 'Promo',
            date: '24 Mei 2024',
            dateISO: '2024-05-24',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWipIQAx0P1KFTsqUPo3ZdXEp8oRh6G-_D81P-lgqNrDKpJz3moZeEAcBaz3RNYEB5LABGjfBvPhtKGdhskSJSFRe-8zjFFCpkz86poq6cn6gbc7Ehu4_ZgcN1gjziGmvDf69JZAyw0SxtdXCz2Swv7ZHxnFVSiIBxizaqhFwWdI8NYCyPc7aWGerA9sGZTe10N8mF7vWsW5-5PR2AW_gf6efE4C8KenIMSrh4fuS7RUpFFB-9MkpkPWyRdLRS0yZZVpCMIy1SvwkL',
            alt: 'Business summit discussion',
            excerpt: 'Agenda tahunan untuk mempertemukan tim, mitra, dan pemangku kepentingan dalam membahas arah transformasi bisnis dan inovasi layanan.',
            lead: 'PT. Mari Sukses Gemilang menyelenggarakan MSG Annual Business Summit sebagai ruang kolaborasi lintas unit untuk memperkuat arah pertumbuhan dan inovasi perusahaan.',
            content: [
                'Kegiatan ini mempertemukan jajaran manajemen, perwakilan unit bisnis, dan mitra strategis untuk membahas tren industri, peluang pertumbuhan, serta strategi penguatan operasional dalam ekosistem MSG.',
                'Melalui sesi diskusi, presentasi, dan lokakarya, perusahaan mendorong setiap unit bisnis untuk semakin adaptif terhadap perubahan perilaku konsumen, perkembangan teknologi, dan kebutuhan pasar lokal.',
                'Summit ini juga menjadi momentum untuk menyelaraskan target jangka panjang perusahaan dengan kualitas layanan, efisiensi operasional, serta pengalaman pelanggan yang lebih konsisten.',
            ],
            quote: {
                text: 'Pertumbuhan yang sehat lahir dari eksekusi yang rapi, kolaborasi yang kuat, dan keberanian untuk terus memperbaiki pengalaman pelanggan.',
                by: 'Management Team MSG',
            },
            tags: ['Business', 'Summit', 'Innovation', 'Collaboration'],
        },
        {
            id: 'green-initiative-2024',
            title: 'Green Initiative 2024: MSG Commits to Net-Zero Construction',
            category: 'Campaign',
            date: '18 Mei 2024',
            dateISO: '2024-05-18',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7MaGEC_P5gJIKUEAY91TTcAlSira-EsbRz3ajn3c92qTtutprJBH8bVLQhehOXtRp4hosv5PnYpShjoCn8SMvvNVYCcD9lwEQkZkdrqwOU1WhZjb-tlPb1OIxy-tFIIzGqESrhuO46wstFh2N7ZRuztsU2MuMSLP0vbRl_ZqNdmoz5mNyhRO6SRXKQvyuNw-dDxyp9-O8xn7TOHkmTfxMyLK82ElhstF7gwg8wEIULTkiD9d-k_V4yKibuZDhuTPNSiGo5T4uDiMs',
            alt: 'Green workspace and sustainable operations',
            excerpt: 'Kerangka keberlanjutan baru untuk memperkuat efisiensi, pengelolaan sumber daya, dan tanggung jawab lingkungan di seluruh operasional perusahaan.',
            lead: 'PT. Mari Sukses Gemilang meluncurkan Green Initiative 2024 sebagai komitmen perusahaan untuk membangun operasional yang lebih efisien, bertanggung jawab, dan berkelanjutan.',
            content: [
                'Inisiatif ini berfokus pada pengurangan konsumsi energi, optimalisasi rantai pasok, serta penerapan kebijakan operasional yang lebih sadar lingkungan di seluruh jaringan bisnis MSG.',
                'Program tersebut mencakup evaluasi penggunaan material, peningkatan efisiensi fasilitas, dan penguatan praktik kerja yang mendukung target keberlanjutan perusahaan dalam jangka panjang.',
                'MSG juga membuka ruang kolaborasi dengan mitra dan komunitas untuk mengembangkan praktik bisnis yang lebih ramah lingkungan tanpa mengurangi kualitas layanan kepada pelanggan.',
            ],
            quote: {
                text: 'Keberlanjutan bukan lagi sekadar tanggung jawab sosial perusahaan; ini adalah bagian dari cara kami membangun bisnis yang relevan untuk masa depan.',
                by: 'Corporate Communications MSG',
            },
            tags: ['Sustainability', 'ESG', 'Operations', 'Green Initiative'],
        },
        {
            id: 'asia-business-awards',
            title: 'MSG Awarded Corporate Excellence at Asia Business Awards',
            category: 'Event',
            date: '12 Mei 2024',
            dateISO: '2024-05-12',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsgGl9h1frD1m7WcImEQjStrPaJH7SP9x5sjNgwxxNyqlNQKKDXVSBJZAZxhzZYVC4BzB-JSchYk2X1ljdcum2dhbFeoUXVFoQyWp06qsE7H_Avo5URrwI3frv1ySTJj3DoNVMY1snzVxR-KGakPDK5LYrZW8rk4o7K17D5QW7-qxmnWcfoqWrRPrwP0Dt5hw5cv91yxn2Cjv5cEvfQvDAWQYPs0JTH2jvL2-iidRiDEivIJqOb_zKMAwGbSYsE4O9cPUvWfTvbvcT',
            alt: 'Corporate award ceremony',
            excerpt: 'Penghargaan ini menjadi pengakuan atas konsistensi perusahaan dalam membangun operasional, layanan, dan portofolio bisnis yang terus berkembang.',
            lead: 'PT. Mari Sukses Gemilang menerima pengakuan Corporate Excellence dalam Asia Business Awards atas kontribusi perusahaan dalam pengembangan bisnis lifestyle dan layanan pelanggan.',
            content: [
                'Penghargaan ini mencerminkan komitmen MSG dalam menjaga kualitas operasional, mengembangkan unit bisnis yang relevan, serta membangun pengalaman pelanggan yang konsisten.',
                'Pencapaian tersebut juga menjadi dorongan bagi perusahaan untuk terus memperkuat standar kerja, memperluas kolaborasi strategis, dan menumbuhkan portofolio bisnis secara bertanggung jawab.',
                'MSG memandang penghargaan ini sebagai hasil kerja kolektif seluruh tim dan mitra yang berperan dalam perjalanan pertumbuhan perusahaan.',
            ],
            quote: {
                text: 'Penghargaan ini adalah pengingat bahwa konsistensi dan kualitas tetap menjadi fondasi utama dalam setiap langkah pertumbuhan kami.',
                by: 'Management Team MSG',
            },
            tags: ['Award', 'Corporate Excellence', 'Event', 'Growth'],
        },
        {
            id: 'msg-ventures-startup-fund',
            title: 'MSG Ventures Mengumumkan Pendanaan untuk Ekosistem Startup',
            category: 'Berita',
            date: '05 Mei 2024',
            dateISO: '2024-05-05',
            author: 'Corporate Communications',
            authorRole: 'PT. Mari Sukses Gemilang',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASGvdwm_Dtl_QzRqM0mQy7K1ojzhb_gZTFy9cp9ayilWFOY-0nRTANIwPNdDrDN3Hmc_UXCZ-WnOY4kv--1uNX6jhUAxSoym8WPUmo_7APKA0PeapGMV0-xRtErjZspRx4bgWCmKhPsr-N_cbahSH4vCZN6div4CGnBES5L472ySCTSGWXJu-DGeD4MYNuXD_1noqW-s-gYhi1c2CMqIOjpgSU07pe3hgZnrDOI2jSx5VlwKRQwFHCLgJA9Y6Xqz14Cpk3OKxgbE6_',
            alt: 'Business partnership discussion',
            excerpt: 'Inisiatif pendanaan tahap awal ditujukan untuk mendukung pertumbuhan ide, teknologi, dan kolaborasi baru di sektor bisnis lokal.',
            lead: 'MSG Ventures memperkenalkan inisiatif pendanaan untuk mendukung ekosistem startup yang memiliki potensi kolaborasi dengan jaringan bisnis perusahaan.',
            content: [
                'Program ini dirancang untuk membuka peluang kerja sama dengan pendiri, komunitas, dan mitra teknologi yang memiliki solusi relevan untuk sektor lifestyle, F&B, retail, dan layanan pelanggan.',
                'Selain pendanaan, MSG Ventures akan menyediakan akses mentoring, validasi pasar, dan peluang pilot project di dalam ekosistem unit bisnis perusahaan.',
                'Inisiatif ini menjadi bagian dari strategi perusahaan untuk mendorong inovasi terbuka dan mempercepat adopsi solusi yang dapat memberi nilai tambah bagi pelanggan.',
            ],
            quote: {
                text: 'Kami ingin membangun jembatan antara ide baru dan kebutuhan nyata di lapangan.',
                by: 'MSG Ventures',
            },
            tags: ['Startup', 'Funding', 'Ventures', 'Innovation'],
        },
    ],

    galleryFilters: [
        { id: 'all', label: 'Semua Galeri' },
        { id: 'fnb', label: 'F&B' },
        { id: 'cafe', label: 'Cafe' },
        { id: 'olahraga', label: 'Olahraga' },
    ],

    galleryItems: [
        {
            title: 'J Chicken Tuparev',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/j-chicken-tprv/j-chicken-tprv-photo-01.jpg',
            alt: 'J Chicken Tuparev',
        },
        {
            title: 'Ulon Signature Tuparev',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-01.jpg',
            alt: 'Ulon Signature Tuparev',
        },
        {
            title: 'Padelnis Sport',
            categoryId: 'olahraga',
            categoryLabel: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-01.jpg',
            alt: 'Padelnis Sport Cirebon',
        },
        {
            title: 'Araichi Ramen',
            categoryId: 'fnb',
            categoryLabel: 'F&B',
            image: 'assets/img/araichi-ramen/araichi-ramen-photo-01.jpg',
            alt: 'Araichi Ramen',
        },
        {
            title: 'Ulon Ciledug',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-coffee-cld/ulon-coffee-cld-photo-01.jpg',
            alt: 'Ulon Coffee Ciledug',
        },
        {
            title: 'Grandmonde',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/GRANDMONDE/grandmonde-photo-01.jpg',
            alt: 'Grandmonde',
        },
        {
            title: 'Interior Ulon Signature',
            categoryId: 'cafe',
            categoryLabel: 'Cafe',
            image: 'assets/img/ulon-signature/ulon-signature-photo-03.jpg',
            alt: 'Ulon Signature Interior',
        },
        {
            title: 'Fasilitas Padelnis Sport',
            categoryId: 'olahraga',
            categoryLabel: 'Olahraga',
            image: 'assets/img/padelnis-sport/padelnis-sport-photo-02.jpg',
            alt: 'Padelnis Sport Facility',
        },
    ],
};
